### ISSUE TITLE
Error while saving video output from zeroscope: ValueError: Image must have 1, 2, 3 or 4 channels

### ISSUE THREAD

**Issue by Abecid** [ubc-vision/vivid123#4]
Traceback (most recent call last):
  File "/workspace/playground/vivid123/run_generation.py", line 23, in <module>
    generation_vivid123(config_path=args.task_yaml_path, vivid123_pipe=vivid123_pipe, xl_pipe=xl_pipe)
  File "/workspace/playground/vivid123/vivid123/generation_utils.py", line 318, in generation_vivid123
    save_videos_grid_zeroscope_nplist(video_xl_frames, f"{output_root_dir}/{cfg.obj_name}/xl.mp4")
  File "/workspace/playground/vivid123/vivid123/generation_utils.py", line 192, in save_videos_grid_zeroscope_nplist
    imageio.imwrite(path, video_frames, fps=fps)
  File "/usr/local/lib/python3.10/dist-packages/imageio/v3.py", line 147, in imwrite
    encoded = img_file.write(image, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/imageio/core/legacy_plugin_wrapper.py", line 253, in write
    writer.append_data(image, metadata)
  File "/usr/local/lib/python3.10/dist-packages/imageio/core/format.py", line 590, in append_data
    return self._append_data(im, total_meta)
  File "/usr/local/lib/python3.10/dist-packages/imageio/plugins/ffmpeg.py", line 584, in _append_data
    raise ValueError("Image must have 1, 2, 3 or 4 channels")
ValueError: Image must have 1, 2, 3 or 4 channels

**Comment by lrf23** [comment]
I meet the same problem with you ,how do you solve the problem
